# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Your name')),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField(max_length=255)),
                ('from_email', models.EmailField(max_length=254, verbose_name='Your e-mail')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
